behaviors:
  MoveToSurvive:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      gail: # Copies the behaviour of the demo and tries to become better than it
        strength: 0.5
        demo_path: Demos/MoveToSurviveDemo.demo
    behavioral_cloning: # Copies the behaviour of the demo
      strength: 0.5
      demo_path: Demos/MoveToSurviveDemo.demo
    max_steps: 500000
    time_horizon: 64
    summary_freq: 50000